# Generated by Django 5.1.1 on 2025-10-15 16:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nome')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('document', models.CharField(blank=True, max_length=32, verbose_name='CNPJ/CPF')),
                ('phone_number', models.CharField(blank=True, max_length=32, verbose_name='Telefone')),
                ('whatsapp_number', models.CharField(blank=True, max_length=32, verbose_name='WhatsApp')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
                ('timezone', models.CharField(default='America/Sao_Paulo', max_length=64, verbose_name='Fuso horário')),
                ('color_primary', models.CharField(default='#D97706', max_length=7, verbose_name='Cor primária')),
                ('color_secondary', models.CharField(default='#1F2937', max_length=7, verbose_name='Cor secundária')),
                ('avatar', models.ImageField(blank=True, upload_to='tenants/logo/', verbose_name='Logo')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
            },
        ),
        migrations.CreateModel(
            name='TenantMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Dono(a)'), ('manager', 'Recepção'), ('professional', 'Profissional'), ('staff', 'Equipe')], default='manager', max_length=32, verbose_name='Papel')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('invited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenant_invites', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='tenants.tenant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vínculo de usuário',
                'verbose_name_plural': 'Vínculos de usuários',
                'unique_together': {('tenant', 'user')},
            },
        ),
    ]
