# Generated by Django 5.1.1 on 2025-10-22 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tenantmembership',
            options={'verbose_name': 'Vinculo de usuario', 'verbose_name_plural': 'Vinculos de usuarios'},
        ),
        migrations.AlterField(
            model_name='tenant',
            name='color_primary',
            field=models.CharField(default='#D97706', max_length=7, verbose_name='Cor primaria'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='color_secondary',
            field=models.CharField(default='#1F2937', max_length=7, verbose_name='Cor secundaria'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='timezone',
            field=models.CharField(default='America/Sao_Paulo', max_length=64, verbose_name='Fuso horario'),
        ),
        migrations.AlterField(
            model_name='tenantmembership',
            name='role',
            field=models.CharField(choices=[('owner', 'Dono(a)'), ('manager', 'Recepcao'), ('professional', 'Profissional'), ('staff', 'Equipe')], default='manager', max_length=32, verbose_name='Papel'),
        ),
    ]
