# Generated by Django 5.1.1 on 2025-10-23 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_alter_tenantmembership_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='label_professional_plural',
            field=models.CharField(default='Profissionais', max_length=50, verbose_name='Label Profissional (plural)'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='label_professional_singular',
            field=models.CharField(default='Profissional', max_length=50, verbose_name='Label Profissional (singular)'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='label_service_plural',
            field=models.CharField(default='Serviços', max_length=50, verbose_name='Label Serviço (plural)'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='label_service_singular',
            field=models.CharField(default='Serviço', max_length=50, verbose_name='Label Serviço (singular)'),
        ),
    ]
