# Generated by Django 4.2.25 on 2025-10-31 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0010_tenant_slot_interval_minutes'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='avatar_base64',
            field=models.TextField(blank=True, null=True, verbose_name='Logo (Base64)'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='label_profissional',
            field=models.CharField(default='Profissional', max_length=50, verbose_name='Nome para Profissional (singular)'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='label_profissional_plural',
            field=models.CharField(default='Profissionais', max_length=50, verbose_name='Nome para Profissional (plural)'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='label_servico',
            field=models.CharField(default='Serviço', max_length=50, verbose_name='Nome para Serviço (singular)'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='label_servico_plural',
            field=models.CharField(default='Serviços', max_length=50, verbose_name='Nome para Serviço (plural)'),
        ),
    ]
