# Generated by Django 4.2.7 on 2025-12-03 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0011_tenant_avatar_base64_tenant_label_profissional_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='about_us',
            field=models.TextField(blank=True, help_text='Descrição sobre o seu negócio/salão', verbose_name='Sobre nós'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='address',
            field=models.CharField(blank=True, max_length=300, verbose_name='Endereço'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='amenities',
            field=models.TextField(blank=True, help_text='Separadas por vírgula: Ex: WiFi, Estacionamento, Acessibilidade', verbose_name='Comodidades'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='city',
            field=models.CharField(blank=True, max_length=100, verbose_name='Cidade'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='facebook_url',
            field=models.URLField(blank=True, verbose_name='URL Facebook'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='instagram_url',
            field=models.URLField(blank=True, verbose_name='URL Instagram'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='neighborhood',
            field=models.CharField(blank=True, max_length=100, verbose_name='Bairro'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='payment_methods',
            field=models.TextField(blank=True, help_text='Separadas por vírgula: Ex: Dinheiro, Cartão de Crédito, Cartão de Débito, PIX', verbose_name='Formas de pagamento'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='state',
            field=models.CharField(blank=True, max_length=2, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='zip_code',
            field=models.CharField(blank=True, max_length=10, verbose_name='CEP'),
        ),
        migrations.CreateModel(
            name='BusinessHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Segunda-feira'), (1, 'Terça-feira'), (2, 'Quarta-feira'), (3, 'Quinta-feira'), (4, 'Sexta-feira'), (5, 'Sábado'), (6, 'Domingo')], verbose_name='Dia da semana')),
                ('is_closed', models.BooleanField(default=False, verbose_name='Fechado')),
                ('opening_time', models.TimeField(blank=True, null=True, verbose_name='Horário de abertura')),
                ('closing_time', models.TimeField(blank=True, null=True, verbose_name='Horário de fechamento')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_hours', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Horário de funcionamento',
                'verbose_name_plural': 'Horários de funcionamento',
                'ordering': ('day_of_week',),
                'unique_together': {('tenant', 'day_of_week')},
            },
        ),
    ]
