# Generated by Django 4.2.25 on 2025-12-04 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0013_brandingsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='brandingsettings',
            name='button_text_color',
            field=models.CharField(default='#FFFFFF', help_text='Cor do texto dentro dos botões', max_length=7, verbose_name='Cor de Texto dos Botões'),
        ),
    ]
