# Generated by Django 4.2.7 on 2025-12-04 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0015_remove_old_branding_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brandingsettings',
            name='button_color_primary',
            field=models.CharField(default='#667EEA', help_text='Cor primária dos botões (a cor secundária do gradiente é gerada automaticamente)', max_length=7, verbose_name='Cor do Botão'),
        ),
        migrations.AlterField(
            model_name='brandingsettings',
            name='button_text_color',
            field=models.CharField(default='#FFFFFF', help_text='Cor do texto dentro dos botões', max_length=7, verbose_name='Cor de Texto do Botão'),
        ),
    ]
