# Generated by Django 4.2.7 on 2025-12-05 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0016_alter_brandingsettings_button_color_primary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='brandingsettings',
            name='button_color_secondary',
            field=models.CharField(default='#764BA2', help_text='Cor secundária (para gradientes)', max_length=7, verbose_name='Cor Secundária do Botão'),
        ),
        migrations.AddField(
            model_name='brandingsettings',
            name='highlight_color',
            field=models.CharField(default='#FBBF24', help_text='Cor para textos em destaque, ícones destacados, contornos especiais', max_length=7, verbose_name='Cor de Destaque'),
        ),
        migrations.AddField(
            model_name='brandingsettings',
            name='use_gradient_buttons',
            field=models.BooleanField(default=True, help_text='Se ativado, botões usarão gradiente com as duas cores. Se desativado, usa apenas a cor primária.', verbose_name='Usar Gradiente nos Botões'),
        ),
        migrations.AlterField(
            model_name='brandingsettings',
            name='button_color_primary',
            field=models.CharField(default='#667EEA', help_text='Cor primária dos botões e destaque', max_length=7, verbose_name='Cor Primária do Botão'),
        ),
        migrations.AlterField(
            model_name='brandingsettings',
            name='button_text_color',
            field=models.CharField(default='#FFFFFF', help_text='Cor do texto dentro dos botões', max_length=7, verbose_name='Cor de Texto dos Botões'),
        ),
    ]
