# Generated by Django 4.2.7 on 2025-12-05 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0017_brandingsettings_button_color_secondary_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brandingsettings',
            name='highlight_color',
        ),
    ]
