# Generated by Django 4.2.7 on 2025-12-05 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0018_remove_brandingsettings_highlight_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='brandingsettings',
            name='highlight_color',
            field=models.CharField(default='#FBBF24', help_text='Cor para textos em destaque, ícones destacados, contornos especiais', max_length=7, verbose_name='Cor de Destaque'),
        ),
    ]
