# Generated by Django 4.2.7 on 2025-12-05 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0019_brandingsettings_highlight_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='contact_info',
            field=models.TextField(blank=True, help_text='Telefone/WhatsApp/e-mail exibidos no site', verbose_name='Contatos do site'),
        ),
    ]
