# Generated by Django 4.2.7 on 2025-12-05 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0020_tenant_contact_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='brandingsettings',
            name='sections_config',
            field=models.JSONField(blank=True, default=dict, help_text='Controla a visibilidade e ordem das seções da página de landing', verbose_name='Configuração de Seções'),
        ),
    ]
