# Generated by Django 4.2.7 on 2025-12-11 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0022_brandingsettings_theme_template'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True, verbose_name='Identificador')),
                ('name', models.CharField(max_length=100, verbose_name='Nome do Plano')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('plan_type', models.CharField(choices=[('free', 'Gratuito'), ('starter', 'Iniciante'), ('professional', 'Profissional'), ('premium', 'Premium'), ('enterprise', 'Enterprise')], default='free', max_length=20, verbose_name='Tipo')),
                ('price_monthly', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Preço Mensal (R$)')),
                ('price_annual', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Preço Anual (R$)')),
                ('max_professionals', models.IntegerField(default=1, help_text='-1 para ilimitado', verbose_name='Máx. Profissionais')),
                ('max_services', models.IntegerField(default=5, help_text='-1 para ilimitado', verbose_name='Máx. Serviços')),
                ('max_monthly_bookings', models.IntegerField(default=100, help_text='-1 para ilimitado', verbose_name='Máx. Agendamentos/mês')),
                ('has_dashboard', models.BooleanField(default=True, verbose_name='Acesso ao Dashboard')),
                ('has_financial_module', models.BooleanField(default=False, verbose_name='Módulo Financeiro')),
                ('has_advanced_analytics', models.BooleanField(default=False, verbose_name='Análises Avançadas')),
                ('has_sms_notifications', models.BooleanField(default=False, verbose_name='Notificações SMS')),
                ('has_email_campaigns', models.BooleanField(default=False, verbose_name='Campanhas por Email')),
                ('has_customer_reviews', models.BooleanField(default=False, verbose_name='Avaliações de Clientes')),
                ('has_custom_domain', models.BooleanField(default=False, verbose_name='Domínio Customizado')),
                ('has_api_access', models.BooleanField(default=False, verbose_name='Acesso à API')),
                ('has_white_label', models.BooleanField(default=False, verbose_name='White Label')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Plano',
                'verbose_name_plural': 'Planos',
                'ordering': ['price_monthly'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Ativo'), ('trial', 'Período de Teste'), ('paused', 'Pausado'), ('cancelled', 'Cancelado'), ('past_due', 'Vencido')], default='trial', max_length=20, verbose_name='Status')),
                ('billing_cycle', models.CharField(choices=[('monthly', 'Mensal'), ('annual', 'Anual')], default='monthly', max_length=20, verbose_name='Ciclo de Cobrança')),
                ('trial_started_at', models.DateTimeField(blank=True, null=True, verbose_name='Teste iniciado em')),
                ('trial_ends_at', models.DateTimeField(blank=True, null=True, verbose_name='Teste termina em')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Subscrição iniciada em')),
                ('next_billing_date', models.DateField(blank=True, null=True, verbose_name='Próxima cobrança')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='Cancelado em')),
                ('payment_method', models.CharField(blank=True, max_length=50, verbose_name='Forma de Pagamento')),
                ('stripe_customer_id', models.CharField(blank=True, max_length=100, verbose_name='Stripe Customer ID')),
                ('stripe_subscription_id', models.CharField(blank=True, max_length=100, verbose_name='Stripe Subscription ID')),
                ('auto_renew', models.BooleanField(default=True, verbose_name='Renovação Automática')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tenants.plan')),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Subscrição',
                'verbose_name_plural': 'Subscrições',
            },
        ),
        migrations.CreateModel(
            name='FeatureUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_name', models.CharField(max_length=100, verbose_name='Feature')),
                ('monthly_usage', models.IntegerField(default=0, verbose_name='Uso Este Mês')),
                ('monthly_limit', models.IntegerField(default=0, verbose_name='Limite Este Mês')),
                ('reset_date', models.DateField(auto_now_add=True, verbose_name='Data do Reset')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature_usage', to='tenants.subscription')),
            ],
            options={
                'verbose_name': 'Uso de Feature',
                'verbose_name_plural': 'Uso de Features',
                'unique_together': {('subscription', 'feature_name')},
            },
        ),
    ]
