# Generated by Django 5.1.1 on 2025-10-23 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='professional',
            name='test_field',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Campo de Teste'),
        ),
    ]
