# Generated by Django 5.1.1 on 2025-10-23 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='professional',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='professionals/avatars/', verbose_name='Foto'),
        ),
    ]
