# Generated by Django 5.1.1 on 2025-10-24 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0002_professional_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='professional',
            name='photo_base64',
            field=models.TextField(blank=True, null=True, verbose_name='Foto (Base64)'),
        ),
    ]
