# Generated by Django 5.1.1 on 2025-10-23 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0002_add_test_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='professional',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='professionals/', verbose_name='Foto'),
        ),
    ]
