# Generated by Django 5.1.1 on 2025-10-23 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0002_add_test_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professional',
            name='test_field',
        ),
        migrations.AddField(
            model_name='professional',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='professionals/', verbose_name='Foto'),
        ),
    ]
