# Generated by Django 5.1.1 on 2025-10-24 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0003_add_photo_base64'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='professional',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='scheduling.professional'),
        ),
    ]
