# Generated by Django 4.2.7 on 2025-12-10 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0022_brandingsettings_theme_template'),
        ('scheduling', '0006_professional_allow_auto_assign'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allow_cancellation', models.BooleanField(default=True, help_text='Permite que clientes cancelem agendamentos', verbose_name='Permitir cancelamento')),
                ('min_cancellation_hours', models.PositiveIntegerField(default=4, help_text='Horas de antecedência necessárias para cancelar', verbose_name='Prazo mínimo para cancelar (horas)')),
                ('max_cancellations', models.PositiveIntegerField(default=3, help_text='Quantidade máxima de cancelamentos no período especificado', verbose_name='Máximo de cancelamentos permitidos')),
                ('cancellation_period_days', models.PositiveIntegerField(default=30, help_text='Período em dias para contar os cancelamentos', verbose_name='Período de contagem (dias)')),
                ('require_cancellation_reason', models.BooleanField(default=False, help_text='Cliente deve informar motivo do cancelamento', verbose_name='Exigir motivo ao cancelar')),
                ('allow_rescheduling', models.BooleanField(default=True, help_text='Permite que clientes reagendem agendamentos', verbose_name='Permitir reagendamento')),
                ('min_reschedule_hours', models.PositiveIntegerField(default=2, help_text='Horas de antecedência necessárias para reagendar', verbose_name='Prazo mínimo para reagendar (horas)')),
                ('max_reschedules_per_booking', models.PositiveIntegerField(default=2, help_text='Quantas vezes o mesmo agendamento pode ser reagendado', verbose_name='Máximo de reagendamentos por agendamento')),
                ('reschedule_window_days', models.PositiveIntegerField(default=60, help_text='Até quantos dias no futuro pode reagendar', verbose_name='Janela para reagendar (dias)')),
                ('block_on_limit_reached', models.BooleanField(default=False, help_text='Bloqueia novos agendamentos ao atingir limite de cancelamentos', verbose_name='Bloquear ao atingir limite')),
                ('block_duration_days', models.PositiveIntegerField(default=15, help_text='Por quantos dias o cliente fica bloqueado', verbose_name='Duração do bloqueio (dias)')),
                ('notify_manager_on_abuse', models.BooleanField(default=True, help_text='Envia notificação quando cliente atinge limite', verbose_name='Notificar gerente sobre abusos')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='booking_policy', to='tenants.tenant', verbose_name='Tenant')),
            ],
            options={
                'verbose_name': 'Política de Agendamento',
                'verbose_name_plural': 'Políticas de Agendamento',
            },
        ),
    ]
