# Generated by Django 4.2.7 on 2025-12-10 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0007_bookingpolicy'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='metadata',
            field=models.JSONField(default=dict, blank=True, verbose_name='Metadados'),
        ),
    ]
