# Generated by Django 4.2.7 on 2025-12-11 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0023_plan_subscription_featureusage'),
        ('scheduling', '0008_add_booking_metadata'),
    ]

    operations = [
        migrations.CreateModel(
            name='Target',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(choices=[('daily', 'Diário'), ('weekly', 'Semanal'), ('monthly', 'Mensal'), ('yearly', 'Anual')], default='monthly', max_length=10)),
                ('target_type', models.CharField(choices=[('revenue', 'Receita'), ('bookings', 'Agendamentos'), ('average_ticket', 'Ticket Médio'), ('confirmed_rate', 'Taxa de Confirmação')], max_length=20)),
                ('target_value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='targets', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Meta',
                'verbose_name_plural': 'Metas',
                'ordering': ('period', 'target_type'),
                'unique_together': {('tenant', 'period', 'target_type')},
            },
        ),
    ]
