# Generated by Django 4.2.7 on 2025-12-15 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0009_add_target_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvolutionAPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instance_id', models.CharField(help_text='Ex: evolution-1, evolution-2', max_length=100, unique=True, verbose_name='ID da Instância')),
                ('url', models.URLField(help_text='Ex: https://seu-dominio.com', verbose_name='URL da API')),
                ('api_key', models.CharField(help_text='Chave de autenticação da instância', max_length=500, verbose_name='API Key')),
                ('capacity', models.IntegerField(default=50, help_text='Máximo recomendado: 50 (conservador: 20, agressivo: 100)', verbose_name='Capacidade (WhatsApps)')),
                ('priority', models.IntegerField(default=10, help_text='Maior número = maior prioridade no load balancing (0-10)', verbose_name='Prioridade')),
                ('is_active', models.BooleanField(default=True, help_text='Se desativada, não será usada para enviar mensagens', verbose_name='Ativa')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Evolution API',
                'verbose_name_plural': 'Evolution APIs',
                'ordering': ['-priority', 'instance_id'],
            },
        ),
        migrations.CreateModel(
            name='WhatsAppInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(help_text='Formato: 5511987654321', max_length=20, verbose_name='Número de WhatsApp')),
                ('display_name', models.CharField(blank=True, help_text='Como o WhatsApp aparece nos contatos', max_length=100, verbose_name='Nome de Exibição')),
                ('connection_status', models.CharField(choices=[('pending', 'Pendente'), ('connecting', 'Conectando'), ('connected', 'Conectado'), ('disconnected', 'Desconectado'), ('error', 'Erro')], default='pending', max_length=20, verbose_name='Status de Conexão')),
                ('is_primary', models.BooleanField(default=False, help_text='WhatsApp principal para agendamentos', verbose_name='Principal')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('evolution_api', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_instances', to='scheduling.evolutionapi', verbose_name='Evolution API')),
            ],
            options={
                'verbose_name': 'WhatsApp Instance',
                'verbose_name_plural': 'WhatsApp Instances',
                'ordering': ['evolution_api', '-is_primary', 'phone_number'],
                'unique_together': {('evolution_api', 'phone_number')},
            },
        ),
    ]
