# Generated by Django 4.2.7 on 2025-12-15 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0023_plan_subscription_featureusage'),
        ('scheduling', '0010_evolutionapi_whatsappinstance'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappinstance',
            name='connected_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Conectado em'),
        ),
        migrations.AddField(
            model_name='whatsappinstance',
            name='connection_code',
            field=models.CharField(blank=True, help_text='Código numérico para conectar', max_length=6, verbose_name='Código de Conexão'),
        ),
        migrations.AddField(
            model_name='whatsappinstance',
            name='disconnected_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Desconectado em'),
        ),
        migrations.AddField(
            model_name='whatsappinstance',
            name='error_message',
            field=models.TextField(blank=True, help_text='Erro da última tentativa de conexão', verbose_name='Mensagem de Erro'),
        ),
        migrations.AddField(
            model_name='whatsappinstance',
            name='qr_code',
            field=models.TextField(blank=True, help_text='Base64 encoded QR code para conectar WhatsApp', verbose_name='QR Code'),
        ),
        migrations.AddField(
            model_name='whatsappinstance',
            name='qr_code_expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='QR Code Expira em'),
        ),
        migrations.AddField(
            model_name='whatsappinstance',
            name='session_id',
            field=models.CharField(blank=True, help_text='ID da sessão no Evolution API', max_length=100, verbose_name='Session ID'),
        ),
        migrations.AddField(
            model_name='whatsappinstance',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_instances', to='tenants.tenant', verbose_name='Inquilino (Dono)'),
        ),
    ]
