# Generated by Django 4.2.7 on 2025-12-16 03:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0011_whatsappinstance_connected_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappinstance',
            name='instance_name',
            field=models.CharField(blank=True, help_text='Nome único da instância no Evolution API (ex: tenant_wa_1)', max_length=100, verbose_name='Nome da Instância'),
        ),
        migrations.AlterField(
            model_name='whatsappinstance',
            name='evolution_api',
            field=models.ForeignKey(blank=True, help_text='(Opcional) Para multi-instâncias Evolution API', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_instances', to='scheduling.evolutionapi', verbose_name='Evolution API'),
        ),
    ]
