# Generated by Django 4.2.25 on 2025-12-26 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0023_plan_subscription_featureusage'),
        ('scheduling', '0012_whatsappinstance_instance_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nome')),
                ('nickname', models.CharField(blank=True, max_length=100, verbose_name='Apelido')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
                ('phone', models.CharField(max_length=32, verbose_name='Celular')),
                ('telephone', models.CharField(blank=True, max_length=32, verbose_name='Telefone')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Aniversário')),
                ('gender', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outro'), ('N', 'Prefiro não informar')], max_length=1, verbose_name='Gênero')),
                ('cpf', models.CharField(blank=True, max_length=14, verbose_name='CPF')),
                ('cnpj', models.CharField(blank=True, max_length=18, verbose_name='CNPJ')),
                ('rg', models.CharField(blank=True, max_length=20, verbose_name='RG')),
                ('referred_by', models.CharField(blank=True, max_length=150, verbose_name='Indicado por')),
                ('tags', models.CharField(blank=True, help_text='Tags separadas por vírgula', max_length=255, verbose_name='Tags')),
                ('cep', models.CharField(blank=True, max_length=10, verbose_name='CEP')),
                ('street', models.CharField(blank=True, max_length=255, verbose_name='Rua')),
                ('number', models.CharField(blank=True, max_length=20, verbose_name='Número')),
                ('complement', models.CharField(blank=True, max_length=100, verbose_name='Complemento')),
                ('neighborhood', models.CharField(blank=True, max_length=100, verbose_name='Bairro')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Cidade')),
                ('state', models.CharField(blank=True, max_length=2, verbose_name='Estado')),
                ('address_notes', models.TextField(blank=True, verbose_name='Observações do endereço')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='customers/', verbose_name='Avatar')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('allow_whatsapp', models.BooleanField(default=True, verbose_name='Permitir WhatsApp')),
                ('allow_sms', models.BooleanField(default=True, verbose_name='Permitir SMS')),
                ('allow_email', models.BooleanField(default=True, verbose_name='Permitir E-mail')),
                ('notes', models.TextField(blank=True, verbose_name='Observações')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ('name',),
                'indexes': [models.Index(fields=['tenant', 'name'], name='scheduling__tenant__1e1fae_idx'), models.Index(fields=['tenant', 'phone'], name='scheduling__tenant__965dee_idx'), models.Index(fields=['tenant', 'email'], name='scheduling__tenant__21b35d_idx')],
            },
        ),
    ]
