version: "3.9"

services:
  web:
    build: .
    # Usa o CMD do Dockerfile (gunicorn em 8000)
    ports:
      - "8000:8000"
    environment:
      DEBUG: ${DEBUG:-false}
      SECRET_KEY: ${SECRET_KEY}
      ALLOWED_HOSTS: ${ALLOWED_HOSTS}
      CSRF_TRUSTED_ORIGINS: ${CSRF_TRUSTED_ORIGINS:-}
      DATABASE_URL: ${DATABASE_URL}
      CELERY_BROKER_URL: ${CELERY_BROKER_URL}
      CELERY_RESULT_BACKEND: ${CELERY_RESULT_BACKEND}
      EVOLUTION_API_URL: ${EVOLUTION_API_URL:-}
      EVOLUTION_API_KEY: ${EVOLUTION_API_KEY:-}
    volumes:
      - media:/app/media

  worker:
    build: .
    command: celery -A config worker -l info
    environment:
      DEBUG: ${DEBUG:-false}
      SECRET_KEY: ${SECRET_KEY}
      ALLOWED_HOSTS: ${ALLOWED_HOSTS}
      CSRF_TRUSTED_ORIGINS: ${CSRF_TRUSTED_ORIGINS:-}
      DATABASE_URL: ${DATABASE_URL}
      CELERY_BROKER_URL: ${CELERY_BROKER_URL}
      CELERY_RESULT_BACKEND: ${CELERY_RESULT_BACKEND}
      EVOLUTION_API_URL: ${EVOLUTION_API_URL:-}
      EVOLUTION_API_KEY: ${EVOLUTION_API_KEY:-}
    volumes:
      - media:/app/media
    depends_on:
      - web

  beat:
    build: .
    command: celery -A config beat -l info
    environment:
      DEBUG: ${DEBUG:-false}
      SECRET_KEY: ${SECRET_KEY}
      ALLOWED_HOSTS: ${ALLOWED_HOSTS}
      CSRF_TRUSTED_ORIGINS: ${CSRF_TRUSTED_ORIGINS:-}
      DATABASE_URL: ${DATABASE_URL}
      CELERY_BROKER_URL: ${CELERY_BROKER_URL}
      CELERY_RESULT_BACKEND: ${CELERY_RESULT_BACKEND}
      EVOLUTION_API_URL: ${EVOLUTION_API_URL:-}
      EVOLUTION_API_KEY: ${EVOLUTION_API_KEY:-}
    volumes:
      - media:/app/media
    depends_on:
      - web

volumes:
  media:
