version: "3.9"

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./src:/app
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis

  worker:
    build: .
    command: celery -A config worker -l info
    volumes:
      - ./src:/app
    env_file:
      - .env
    depends_on:
      - web
      - redis

  beat:
    build: .
    command: celery -A config beat -l info
    volumes:
      - ./src:/app
    env_file:
      - .env
    depends_on:
      - web
      - redis

  db:
    image: postgres:16
    environment:
      POSTGRES_DB: barber
      POSTGRES_USER: barber
      POSTGRES_PASSWORD: barber
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:
