# Generated by Django 4.2.25 on 2025-12-17 18:24

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0023_plan_subscription_featureusage'),
        ('scheduling', '0012_whatsappinstance_instance_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('account_type', models.CharField(choices=[('cash', 'Dinheiro'), ('bank', 'Banco'), ('card', 'Cartão'), ('pix', 'PIX')], max_length=20)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_accounts', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Conta Financeira',
                'verbose_name_plural': 'Contas Financeiras',
                'db_table': 'financial_account',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('income', 'Receita'), ('expense', 'Despesa'), ('transfer', 'Transferência')], max_length=20)),
                ('payment_method', models.CharField(choices=[('cash', 'Dinheiro'), ('card_credit', 'Cartão Crédito'), ('card_debit', 'Cartão Débito'), ('pix', 'PIX'), ('bank_transfer', 'Transferência Bancária'), ('check', 'Cheque')], max_length=20)),
                ('description', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('transaction_date', models.DateField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='financial.account')),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='financial_transactions', to='scheduling.booking')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_transactions', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Transação',
                'verbose_name_plural': 'Transações',
                'db_table': 'financial_transaction',
                'ordering': ['-transaction_date', '-created_at'],
                'indexes': [models.Index(fields=['tenant', '-transaction_date'], name='financial_t_tenant__2a1227_idx'), models.Index(fields=['account', '-transaction_date'], name='financial_t_account_70cdc0_idx')],
            },
        ),
        migrations.CreateModel(
            name='Commission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commission_type', models.CharField(default='percentage', help_text='Tipo: percentage ou fixed_amount', max_length=50)),
                ('commission_value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('paid', 'Pago'), ('cancelled', 'Cancelado')], default='pending', max_length=20)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='commission', to='scheduling.booking')),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commissions', to='scheduling.professional')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_commissions', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Comissão',
                'verbose_name_plural': 'Comissões',
                'db_table': 'financial_commission',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant', 'status'], name='financial_c_tenant__f272ea_idx'), models.Index(fields=['professional', '-created_at'], name='financial_c_profess_4654e8_idx')],
            },
        ),
    ]
